server:
  port: 8080
spring:
  profiles:
    active: default
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

jwt:
  secret: ${JWT_SECRET:RedNorteClaveSecretaSuperSegura2024BFF}

resilience4j.circuitbreaker:
  instances:
    lista-espera:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
    reasignacion:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
    pacientes:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
    auth:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s

ms:
  auth:
    url: ${MS_AUTH_URL:http://localhost:8084}
  lista-espera:
    url: ${MS_LISTA_ESPERA_URL:http://localhost:8081}
  reasignacion:
    url: ${MS_REASIGNACION_URL:http://localhost:8082}
  pacientes:
    url: ${MS_PACIENTES_URL:http://localhost:8083}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:h2:mem:bff;DB_CLOSE_DELAY=-1
    username: sa
    password:

ms:
  auth:
    url: ${MS_AUTH_URL:http://ms-auth:8084}
  lista-espera:
    url: ${MS_LISTA_ESPERA_URL:http://ms-lista-espera:8081}
  reasignacion:
    url: ${MS_REASIGNACION_URL:http://ms-reasignacion:8082}
  pacientes:
    url: ${MS_PACIENTES_URL:http://ms-pacientes:8083}
